-- =============================================================================
-- Migration 002: Create inquiries table
-- =============================================================================
-- An inquiry is created the moment a patient starts a chat session and provides
-- enough information for the agent to begin matching. One inquiry → at most one
-- appointment (we enforce this at the application layer, not DB, to keep the
-- schema flexible for rescheduling later).
--
-- Design decisions:
--   - patient_identifier is a hashed or anonymized reference (e.g. SHA256 of
--     email+phone). We deliberately avoid storing raw PII in this column for
--     HIPAA reasons. The actual contact details stay in the chat session only.
--   - extracted_conditions is TEXT[] populated by the extractPatientInfo tool.
--     Storing it here lets admins see what the AI understood without re-running
--     the extraction.
--   - status uses a CHECK constraint with a defined state machine:
--       pending → matched → availability_checked → scheduled → cancelled → failed
--   - raw_chat_summary is a short LLM-generated summary stored for admin review.
--     Not the full conversation (that lives in conversation_sessions).
-- =============================================================================

BEGIN;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.tables
    WHERE table_schema = 'public'
    AND table_name = 'inquiries'
  ) THEN

    -- Ensure therapists exists before creating FK
    IF NOT EXISTS (
      SELECT 1 FROM information_schema.tables
      WHERE table_schema = 'public' AND table_name = 'therapists'
    ) THEN
      RAISE EXCEPTION '[002] therapists table must exist before inquiries — run 001 first';
    END IF;

    CREATE TABLE public.inquiries (
      -- Primary key
      id                      UUID          PRIMARY KEY DEFAULT gen_random_uuid(),

      -- Patient identity (anonymized — no raw PII stored here)
      -- Format: 'anon_<first8charsOfSHA256(email)>' or 'session_<uuid>'
      patient_identifier      TEXT          NOT NULL,

      -- Raw input from patient (captured early in the conversation)
      problem_description     TEXT          NOT NULL DEFAULT '',
      requested_schedule      TEXT          NOT NULL DEFAULT '',
      insurance_info          TEXT          NOT NULL DEFAULT '',

      -- Structured data extracted by the AI agent's extractPatientInfo tool
      -- Example: ARRAY['anxiety', 'PTSD', 'depression']
      extracted_conditions    TEXT[]        NOT NULL DEFAULT '{}',
      -- The primary specialty the agent decided to match on
      primary_specialty       TEXT,

      -- Matching result — populated by findMatchingTherapists tool
      matched_therapist_id    UUID          REFERENCES public.therapists(id) ON DELETE SET NULL,
      -- All therapist IDs considered during matching (for admin analytics)
      considered_therapist_ids UUID[]       NOT NULL DEFAULT '{}',

      -- State machine for the inquiry lifecycle
      -- pending            → inquiry created, agent collecting info
      -- matched            → therapist matched, checking availability
      -- availability_checked → slots found, presented to patient
      -- scheduled          → appointment booked on Google Calendar
      -- cancelled          → patient or admin cancelled
      -- failed             → agent could not complete (no match, calendar error, etc.)
      status                  TEXT          NOT NULL DEFAULT 'pending'
                              CHECK (status IN (
                                'pending',
                                'matched',
                                'availability_checked',
                                'scheduled',
                                'cancelled',
                                'failed'
                              )),

      -- Short summary generated by AI for admin review
      -- Max 500 chars — not the full conversation
      raw_chat_summary        TEXT          CHECK (char_length(raw_chat_summary) <= 500),

      -- Failure tracking
      failure_reason          TEXT,
      -- How many agent loop iterations this inquiry required (for performance monitoring)
      agent_loop_count        INTEGER       NOT NULL DEFAULT 0,

      -- Audit
      created_at              TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
      updated_at              TIMESTAMPTZ   NOT NULL DEFAULT NOW()
    );

    -- Agent queries inquiries by status and therapist for admin dashboard
    CREATE INDEX idx_inquiries_status
      ON public.inquiries (status, created_at DESC);

    CREATE INDEX idx_inquiries_therapist
      ON public.inquiries (matched_therapist_id)
      WHERE matched_therapist_id IS NOT NULL;

    CREATE INDEX idx_inquiries_patient
      ON public.inquiries (patient_identifier);

    -- GIN index on extracted_conditions for analytics queries
    CREATE INDEX idx_inquiries_conditions
      ON public.inquiries USING GIN (extracted_conditions);

    CREATE TRIGGER inquiries_updated_at
      BEFORE UPDATE ON public.inquiries
      FOR EACH ROW EXECUTE FUNCTION public.handle_updated_at();

    RAISE NOTICE '[002] inquiries table created successfully';

  ELSE
    RAISE NOTICE '[002] inquiries table already exists — skipping';
  END IF;
END $$;

COMMIT;